// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyectocemilla_verde.Context;

#nullable disable

namespace Proyectocemillaverde.Migrations
{
    [DbContext(typeof(Aplication_DB_Context.AplicationdbContext))]
    [Migration("20230217165124_example")]
    partial class example
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entity.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("Domain.Entity.Empledo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FKdepartamento")
                        .HasColumnType("int");

                    b.Property<int?>("FKpuesto")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKdepartamento");

                    b.HasIndex("FKpuesto");

                    b.ToTable("Empledos");
                });

            modelBuilder.Entity("Domain.Entity.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Puesto");
                });

            modelBuilder.Entity("Domain.Entity.Empledo", b =>
                {
                    b.HasOne("Domain.Entity.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("FKdepartamento");

                    b.HasOne("Domain.Entity.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("FKpuesto");

                    b.Navigation("Departamento");

                    b.Navigation("Puesto");
                });
#pragma warning restore 612, 618
        }
    }
}
